package com.zuowen.magic.db.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MAGIC_LIST".
 */
public class MagicList {

    private Long id;
    private String pid;
    private String aid;
    private String title;
    private String url;
    private String intro;
    private String cid;
    private String author;
    private String date;
    private String classname;
    private String tags;
    private Boolean collect;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MagicList() {
    }

    public MagicList(Long id) {
        this.id = id;
    }

    public MagicList(Long id, String pid, String aid, String title, String url, String intro, String cid, String author, String date, String classname, String tags, Boolean collect) {
        this.id = id;
        this.pid = pid;
        this.aid = aid;
        this.title = title;
        this.url = url;
        this.intro = intro;
        this.cid = cid;
        this.author = author;
        this.date = date;
        this.classname = classname;
        this.tags = tags;
        this.collect = collect;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getAid() {
        return aid;
    }

    public void setAid(String aid) {
        this.aid = aid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getClassname() {
        return classname;
    }

    public void setClassname(String classname) {
        this.classname = classname;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public Boolean getCollect() {
        return collect;
    }

    public void setCollect(Boolean collect) {
        this.collect = collect;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
