package com.zuowen.magic.db.dao;

import android.database.sqlite.SQLiteDatabase;

import com.zuowen.magic.db.model.MagicList;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig magicListDaoConfig;

    private final MagicListDao magicListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        magicListDaoConfig = daoConfigMap.get(MagicListDao.class).clone();
        magicListDaoConfig.initIdentityScope(type);

        magicListDao = new MagicListDao(magicListDaoConfig, this);

        registerDao(MagicList.class, magicListDao);
    }
    
    public void clear() {
        magicListDaoConfig.getIdentityScope().clear();
    }

    public MagicListDao getMagicListDao() {
        return magicListDao;
    }

}
