package com.zuowen.magic.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.zuowen.magic.db.model.MagicList;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "MAGIC_LIST".
*/
public class MagicListDao extends AbstractDao<MagicList, Long> {

    public static final String TABLENAME = "MAGIC_LIST";

    /**
     * Properties of entity MagicList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Pid = new Property(1, String.class, "pid", false, "PID");
        public final static Property Aid = new Property(2, String.class, "aid", false, "AID");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Url = new Property(4, String.class, "url", false, "URL");
        public final static Property Intro = new Property(5, String.class, "intro", false, "INTRO");
        public final static Property Cid = new Property(6, String.class, "cid", false, "CID");
        public final static Property Author = new Property(7, String.class, "author", false, "AUTHOR");
        public final static Property Date = new Property(8, String.class, "date", false, "DATE");
        public final static Property Classname = new Property(9, String.class, "classname", false, "CLASSNAME");
        public final static Property Tags = new Property(10, String.class, "tags", false, "TAGS");
        public final static Property Collect = new Property(11, Boolean.class, "collect", false, "COLLECT");
    };


    public MagicListDao(DaoConfig config) {
        super(config);
    }
    
    public MagicListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MAGIC_LIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PID\" TEXT," + // 1: pid
                "\"AID\" TEXT," + // 2: aid
                "\"TITLE\" TEXT," + // 3: title
                "\"URL\" TEXT," + // 4: url
                "\"INTRO\" TEXT," + // 5: intro
                "\"CID\" TEXT," + // 6: cid
                "\"AUTHOR\" TEXT," + // 7: author
                "\"DATE\" TEXT," + // 8: date
                "\"CLASSNAME\" TEXT," + // 9: classname
                "\"TAGS\" TEXT," + // 10: tags
                "\"COLLECT\" INTEGER);"); // 11: collect
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MAGIC_LIST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MagicList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String pid = entity.getPid();
        if (pid != null) {
            stmt.bindString(2, pid);
        }
 
        String aid = entity.getAid();
        if (aid != null) {
            stmt.bindString(3, aid);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
 
        String intro = entity.getIntro();
        if (intro != null) {
            stmt.bindString(6, intro);
        }
 
        String cid = entity.getCid();
        if (cid != null) {
            stmt.bindString(7, cid);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(8, author);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(9, date);
        }
 
        String classname = entity.getClassname();
        if (classname != null) {
            stmt.bindString(10, classname);
        }
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(11, tags);
        }
 
        Boolean collect = entity.getCollect();
        if (collect != null) {
            stmt.bindLong(12, collect ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MagicList readEntity(Cursor cursor, int offset) {
        MagicList entity = new MagicList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // pid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // aid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // url
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // intro
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // cid
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // author
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // date
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // classname
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // tags
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0 // collect
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MagicList entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIntro(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCid(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAuthor(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDate(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setClassname(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTags(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCollect(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MagicList entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MagicList entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
